(() => {
  const $ = selector => document.querySelector(selector);
  const MODEL = {
    deepseek: {label:'DeepSeek V4 Flash 0731', color:'#9ac641', cls:'deepseek'},
    luna: {label:'GPT‑5.6 Luna', color:'#58c9f5', cls:'luna'}
  };
  const state = {runs:[], policies:[], timelines:new Map(), filter:'story'};
  const finite = value => typeof value === 'number' && Number.isFinite(value);
  const groupBy = (rows,key) => rows.reduce((out,row)=>{const value=key(row);(out[value]??=[]).push(row);return out},{});
  const family = model => String(model||'').toLowerCase().includes('deepseek') ? 'deepseek' : String(model||'').toLowerCase().includes('luna') ? 'luna' : null;
  const fmtMoney = value => finite(value) ? `$${value.toFixed(value < 10 ? 2 : 0)}` : '—';
  const fmtTime = ms => finite(ms) ? (ms/3600000).toFixed(1)+' h' : '—';
  const esc = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function json(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw Error(`${path}: ${response.status}`);return response.json()}
  function svg(tag,attrs={}){const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,value);return node}
  function chart(target, points, xKey, xLabel){
    const el=$(target), width=1000, height=500, p={l:68,r:24,t:34,b:54};el.replaceChildren();el.setAttribute('viewBox',`0 0 ${width} ${height}`);
    const valid=points.filter(d=>finite(d.y)&&finite(d[xKey]));
    const xmax=Math.max(1,...valid.map(d=>d[xKey])), ymin=Math.min(5,...valid.map(d=>d.y)), ymax=Math.max(60,...valid.map(d=>d.y));
    const x=v=>p.l+v/xmax*(width-p.l-p.r), y=v=>p.t+(ymax-v)/(ymax-ymin)*(height-p.t-p.b);
    for(let i=0;i<=5;i++){const yy=p.t+i*(height-p.t-p.b)/5,val=ymax-i*(ymax-ymin)/5;el.append(svg('line',{x1:p.l,x2:width-p.r,y1:yy,y2:yy,class:'gridline'}));const t=svg('text',{x:p.l-10,y:yy+4,'text-anchor':'end',class:'chart-label'});t.textContent=`${val.toFixed(0)}s`;el.append(t)}
    for(let i=0;i<=5;i++){const xx=p.l+i*(width-p.l-p.r)/5,val=i*xmax/5;const t=svg('text',{x:xx,y:height-20,'text-anchor':'middle',class:'chart-label'});t.textContent=xKey==='cost'?fmtMoney(val):`${val.toFixed(1)}h`;el.append(t)}
    const label=svg('text',{x:width/2,y:height-3,'text-anchor':'middle',class:'chart-label'});label.textContent=xLabel;el.append(label);
    const byRun=groupBy(valid,d=>d.run_id);for(const [run, rows] of Object.entries(byRun)){rows.sort((a,b)=>a[xKey]-b[xKey]);let best=Infinity,path='';for(const row of rows){best=Math.min(best,row.y);path+=`${path?'L':'M'}${x(row[xKey])},${y(best)} `}const f=family(rows[0].model),line=svg('path',{d:path,class:'best-line',stroke:MODEL[f].color,opacity:.55});el.append(line);for(const row of rows){const dot=svg('circle',{cx:x(row[xKey]),cy:y(row.y),r:5,fill:MODEL[f].color,class:'submission'});dot.append(document.createElementNS('http://www.w3.org/2000/svg','title')).textContent=`${run} · ${row.y.toFixed(3)}s`;el.append(dot)}}
    if(!valid.length){const t=svg('text',{x:width/2,y:height/2,'text-anchor':'middle',class:'chart-label'});t.textContent='Waiting for valid scored policies';el.append(t)}
  }
  function renderCards(){const groups=groupBy(state.runs,r=>family(r.model));$('#model-cards').innerHTML=['deepseek','luna'].map(key=>{const runs=groups[key]||[],times=runs.map(r=>r.timeline?.comparison_summary?.best_100m_s).filter(finite),best=times.length?Math.min(...times):null,complete=runs.filter(r=>r.timeline?.coverage?.ready).length;return `<article class="model-card ${key}"><div><div class="model-name">${MODEL[key].label}</div><div class="model-meta">${runs.length}/3 trials discovered · ${complete} finalized<br>Codex 0.147.0 · max reasoning</div></div><div class="model-stat">${best?best.toFixed(3)+'s':'—'}</div></article>`}).join('')}
  function renderPolicies(){let rows=[...state.policies];if(state.filter==='failures')rows=rows.filter(p=>!p.valid_run);if(state.filter==='valid')rows=rows.filter(p=>p.valid_run);if(state.filter==='story'){const firstFailure=new Map(), selected=[];for(const p of rows){const key=`${p.run_id}:${(p.failed_gates||[]).join(',')||'no-finish'}`;if(!p.valid_run&&!firstFailure.has(key)){firstFailure.set(key,true);selected.push(p)}else if(p.valid_run&&(p.on_frontier||p.replay_ready))selected.push(p)}rows=selected}rows.sort((a,b)=>String(b.finished_at||'').localeCompare(String(a.finished_at||'')));$('#policy-grid').innerHTML=rows.length?rows.slice(0,state.filter==='all'?400:80).map(p=>{const f=family(p.model),result=p.valid_run?`${Number(p.best_100m_s).toFixed(3)} s`:'DQ / DNF',detail=p.valid_run?`${finite(p.peak_speed_mps)?p.peak_speed_mps.toFixed(2)+' m/s peak':''}${p.on_frontier?' · Pareto frontier':''}`:`${(p.failed_gates||['no valid finish']).join(' · ')}${finite(p.max_distance_m)?` · ${p.max_distance_m.toFixed(1)} m`:''}`;return `<article class="policy-card ${p.valid_run?'valid':'failure'}"><div class="policy-top"><span>${MODEL[f]?.label||esc(p.model)}</span><span>${esc(p.run_id.split('-').slice(-1)[0])} / #${p.submission_index}</span></div><div class="policy-result">${result}</div><div class="policy-detail">${esc(detail)}</div><div class="policy-actions">${p.replay_ready?`<a href="${esc(p.replay_url)}">Full-screen replay ↗</a>`:'<span class="tag">replay processing</span>'}<span class="tag">${p.valid_run?'valid':'failure'}</span></div></article>`}).join(''):'<p class="empty">Waiting for the first scored policy…</p>'}
  function renderResources(){const rows=[];for(const run of state.runs){const summary=run.timeline?.resource_usage_summary||{},estimate=summary.modal_estimate?.by_role||{};for(const [role,label] of [['cpu_agent','CPU agent'],['training_gpu','Training GPU'],['verifier_gpu','Verifier GPU']]){const value=Number(estimate[role]?.estimated_cost_usd||0);rows.push({family:family(run.model),role,label,value})}}const aggregate={};for(const row of rows){const key=`${row.family}:${row.role}`;aggregate[key]=(aggregate[key]||0)+row.value}const max=Math.max(.01,...Object.values(aggregate));$('#resource-bars').innerHTML=['deepseek','luna'].flatMap(f=>[['cpu_agent','CPU agent'],['training_gpu','Training GPU'],['verifier_gpu','Verifier GPU']].map(([role,label])=>{const value=aggregate[`${f}:${role}`]||0;return `<div class="resource-row"><span>${MODEL[f].label.split(' ')[0]}<br>${label}</span><div class="bar"><i style="width:${100*value/max}%;background:${MODEL[f].color};opacity:${role==='verifier_gpu'?.45:role==='cpu_agent'?.7:1}"></i></div><b>${fmtMoney(value)}</b></div>`})).join('')||'<p class="empty">Resource allocations appear as trials start.</p>'}
  function renderRuns(){const links=state.runs.map(run=>{const t=run.timeline,summary=t?.comparison_summary||{};return `<a class="run-link" href="/timeline?run=${encodeURIComponent(run.run_id)}"><b>${esc(run.run_id)}</b><span>${MODEL[family(run.model)]?.label||esc(run.model)} · ${t?.coverage?.ready?'finalized':'live / incomplete'}<br>${fmtTime(summary.wall_duration_ms)} · ${summary.tool_call_count??0} tool calls · ${fmtMoney(summary.final_total_cost_usd)}</span></a>`});$('#run-links').innerHTML=links.join('')||'<p class="empty">Trials have not started.</p>'}
  function render(){renderCards();const points=[];for(const run of state.runs){const t=run.timeline;if(!t)continue;for(const a of t.artifacts||[]){if(Number(a.rewards?.valid_run)!==1)continue;const result=a.cost_at_result||{};points.push({run_id:run.run_id,model:run.model,y:Number(a.rewards.best_100m_s),hours:(Number(result.epoch_ms||a.finished_epoch_ms)-t.clock.origin_epoch_ms)/3600000,cost:Number(result.total_estimated_usd)})}}chart('#time-chart',points,'hours','hours since agent launch');chart('#cost-chart',points,'cost','estimated agent cost at result');$('#time-legend').innerHTML=['deepseek','luna'].map(f=>`<span><i style="background:${MODEL[f].color}"></i>${MODEL[f].label}</span>`).join('');renderResources();renderPolicies();renderRuns();const updated=state.runs.map(r=>r.updated_at).filter(Boolean).sort().at(-1);$('#updated').textContent=updated?`Updated ${new Date(updated).toLocaleString()}`:'No experiment data deployed yet';$('#live').textContent=state.runs.some(r=>!r.timeline?.coverage?.ready)?'● trials live':'experiment archive';$('#live').classList.toggle('on',state.runs.some(r=>!r.timeline?.coverage?.ready))}
  async function init(){try{const [pIndex,tIndex]=await Promise.all([json('/data/policies/index.json').catch(()=>({runs:[]})),json('/data/timelines/index.json').catch(()=>({runs:[]}))]);const selected=pIndex.runs.filter(r=>family(r.model)).sort((a,b)=>`${b.created_at||''}:${b.run_id||''}`.localeCompare(`${a.created_at||''}:${a.run_id||''}`)).slice(0,6);for(const meta of selected){const p=await json(meta.path);const tMeta=tIndex.runs.find(row=>row.run_id===meta.run_id);const timeline=tMeta?await json(tMeta.path):null;const run={...meta,timeline};state.runs.push(run);for(const policy of p.policies||[])state.policies.push({...policy,run_id:p.run_id,model:p.model})}render()}catch(error){$('#updated').textContent=`Data error: ${error.message}`;console.error(error)}}
  $('#filters').addEventListener('click',event=>{const button=event.target.closest('[data-filter]');if(!button)return;state.filter=button.dataset.filter;for(const item of $('#filters').querySelectorAll('button'))item.classList.toggle('active',item===button);renderPolicies()});init();
})();
